# Generated by Django 6.0.2 on 2026-02-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('mob', models.CharField(max_length=15)),
            ],
        ),
    ]
